---
title: "Tempo Analysis Report"
author: '`r Sys.info()[["user"]] `'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    keep_tex: yes
    number_sections: yes
    toc: yes
    df_print: kable
  html_document:
    df_print: paged
    keep_md: yes
    number_sections: yes
    toc: yes
params:
  mapping_file: mapping.tsv
  pairing_file: pairing.tsv
  output_dir: output
  analysis_config_json: config.json

---
```{r setup, include=FALSE}
# set up configs for use in the report
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.height = 20)
knitr::opts_chunk$set(fig.width = 20)
library("ggplot2") 
library("jsonlite")
library("knitr")
library("reshape2")
library("DT")
```

```{r, load_data}
# load all data that will be used in the report
child_docs <- c("samples.Rmd", "qc.Rmd", "overview.Rmd")
mapping <- read.delim(file = params$mapping_file, header = TRUE, sep = '\t')
pairing <- read.delim(file = params$pairing_file, header = TRUE, sep = '\t')
location <- getwd()
config <- fromJSON(params$analysis_config_json, flatten=TRUE)
sample_data_file <- file.path(params$output_dir, "cohort_level", "default_cohort", "sample_data.txt")
concordance_data_file <- file.path(params$output_dir, "cohort_level", "default_cohort", "concordance_qc.txt")
alignment_qc_file <- file.path(params$output_dir, "cohort_level", "default_cohort", "alignment_qc.txt")
contamination_file <- file.path(params$output_dir, "cohort_level", "default_cohort", "contamination_qc.txt")
```

```{r compile_child, results='asis'}
# load and compile each child doc
for(child_doc in child_docs){
    cat(knit_child(child_doc, quiet = TRUE))
    cat('\n')
}
```

```{r save_image, include=FALSE}
save.image(file="report.Rdata",compress = TRUE)
```